// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: proto/paxoskv.proto

package paxoskv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BallotNum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	N          int64 `protobuf:"varint,1,opt,name=N,proto3" json:"N,omitempty"`
	ProposerId int64 `protobuf:"varint,2,opt,name=ProposerId,proto3" json:"ProposerId,omitempty"`
}

func (x *BallotNum) Reset() {
	*x = BallotNum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paxoskv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BallotNum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BallotNum) ProtoMessage() {}

func (x *BallotNum) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxoskv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BallotNum.ProtoReflect.Descriptor instead.
func (*BallotNum) Descriptor() ([]byte, []int) {
	return file_proto_paxoskv_proto_rawDescGZIP(), []int{0}
}

func (x *BallotNum) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *BallotNum) GetProposerId() int64 {
	if x != nil {
		return x.ProposerId
	}
	return 0
}

type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vi64 int64 `protobuf:"varint,1,opt,name=Vi64,proto3" json:"Vi64,omitempty"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paxoskv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxoskv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_proto_paxoskv_proto_rawDescGZIP(), []int{1}
}

func (x *Value) GetVi64() int64 {
	if x != nil {
		return x.Vi64
	}
	return 0
}

type PaxosInstanceID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Ver int64  `protobuf:"varint,2,opt,name=Ver,proto3" json:"Ver,omitempty"`
}

func (x *PaxosInstanceID) Reset() {
	*x = PaxosInstanceID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paxoskv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaxosInstanceID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaxosInstanceID) ProtoMessage() {}

func (x *PaxosInstanceID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxoskv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaxosInstanceID.ProtoReflect.Descriptor instead.
func (*PaxosInstanceID) Descriptor() ([]byte, []int) {
	return file_proto_paxoskv_proto_rawDescGZIP(), []int{2}
}

func (x *PaxosInstanceID) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PaxosInstanceID) GetVer() int64 {
	if x != nil {
		return x.Ver
	}
	return 0
}

type PrepareReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  *PaxosInstanceID `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Bal *BallotNum       `protobuf:"bytes,2,opt,name=Bal,proto3" json:"Bal,omitempty"`
}

func (x *PrepareReq) Reset() {
	*x = PrepareReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paxoskv_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrepareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareReq) ProtoMessage() {}

func (x *PrepareReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxoskv_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareReq.ProtoReflect.Descriptor instead.
func (*PrepareReq) Descriptor() ([]byte, []int) {
	return file_proto_paxoskv_proto_rawDescGZIP(), []int{3}
}

func (x *PrepareReq) GetID() *PaxosInstanceID {
	if x != nil {
		return x.ID
	}
	return nil
}

func (x *PrepareReq) GetBal() *BallotNum {
	if x != nil {
		return x.Bal
	}
	return nil
}

type PrepareResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastBal *BallotNum `protobuf:"bytes,1,opt,name=LastBal,proto3" json:"LastBal,omitempty"`
	Val     *Value     `protobuf:"bytes,2,opt,name=Val,proto3" json:"Val,omitempty"`
	VBal    *BallotNum `protobuf:"bytes,3,opt,name=VBal,proto3" json:"VBal,omitempty"`
}

func (x *PrepareResp) Reset() {
	*x = PrepareResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paxoskv_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrepareResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareResp) ProtoMessage() {}

func (x *PrepareResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxoskv_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareResp.ProtoReflect.Descriptor instead.
func (*PrepareResp) Descriptor() ([]byte, []int) {
	return file_proto_paxoskv_proto_rawDescGZIP(), []int{4}
}

func (x *PrepareResp) GetLastBal() *BallotNum {
	if x != nil {
		return x.LastBal
	}
	return nil
}

func (x *PrepareResp) GetVal() *Value {
	if x != nil {
		return x.Val
	}
	return nil
}

func (x *PrepareResp) GetVBal() *BallotNum {
	if x != nil {
		return x.VBal
	}
	return nil
}

type AcceptReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  *PaxosInstanceID `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Bal *BallotNum       `protobuf:"bytes,2,opt,name=Bal,proto3" json:"Bal,omitempty"`
	Val *Value           `protobuf:"bytes,3,opt,name=Val,proto3" json:"Val,omitempty"`
}

func (x *AcceptReq) Reset() {
	*x = AcceptReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paxoskv_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptReq) ProtoMessage() {}

func (x *AcceptReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxoskv_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptReq.ProtoReflect.Descriptor instead.
func (*AcceptReq) Descriptor() ([]byte, []int) {
	return file_proto_paxoskv_proto_rawDescGZIP(), []int{5}
}

func (x *AcceptReq) GetID() *PaxosInstanceID {
	if x != nil {
		return x.ID
	}
	return nil
}

func (x *AcceptReq) GetBal() *BallotNum {
	if x != nil {
		return x.Bal
	}
	return nil
}

func (x *AcceptReq) GetVal() *Value {
	if x != nil {
		return x.Val
	}
	return nil
}

type AcceptResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OK      bool       `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	LastBal *BallotNum `protobuf:"bytes,2,opt,name=LastBal,proto3" json:"LastBal,omitempty"`
}

func (x *AcceptResp) Reset() {
	*x = AcceptResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paxoskv_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptResp) ProtoMessage() {}

func (x *AcceptResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxoskv_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptResp.ProtoReflect.Descriptor instead.
func (*AcceptResp) Descriptor() ([]byte, []int) {
	return file_proto_paxoskv_proto_rawDescGZIP(), []int{6}
}

func (x *AcceptResp) GetOK() bool {
	if x != nil {
		return x.OK
	}
	return false
}

func (x *AcceptResp) GetLastBal() *BallotNum {
	if x != nil {
		return x.LastBal
	}
	return nil
}

var File_proto_paxoskv_proto protoreflect.FileDescriptor

var file_proto_paxoskv_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x6b, 0x76, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x6b, 0x76, 0x22, 0x39,
	0x0a, 0x09, 0x42, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x0c, 0x0a, 0x01, 0x4e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x4e, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x72, 0x6f,
	0x70, 0x6f, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x50,
	0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x1b, 0x0a, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x56, 0x69, 0x36, 0x34, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x56, 0x69, 0x36, 0x34, 0x22, 0x35, 0x0a, 0x0f, 0x50, 0x61, 0x78, 0x6f, 0x73, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x56,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x56, 0x65, 0x72, 0x22, 0x5c, 0x0a,
	0x0a, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x28, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x6b,
	0x76, 0x2e, 0x50, 0x61, 0x78, 0x6f, 0x73, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49,
	0x44, 0x52, 0x02, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x03, 0x42, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x6b, 0x76, 0x2e, 0x42, 0x61, 0x6c,
	0x6c, 0x6f, 0x74, 0x4e, 0x75, 0x6d, 0x52, 0x03, 0x42, 0x61, 0x6c, 0x22, 0x85, 0x01, 0x0a, 0x0b,
	0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x07, 0x4c,
	0x61, 0x73, 0x74, 0x42, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70,
	0x61, 0x78, 0x6f, 0x73, 0x6b, 0x76, 0x2e, 0x42, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x4e, 0x75, 0x6d,
	0x52, 0x07, 0x4c, 0x61, 0x73, 0x74, 0x42, 0x61, 0x6c, 0x12, 0x20, 0x0a, 0x03, 0x56, 0x61, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x6b, 0x76,
	0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x03, 0x56, 0x61, 0x6c, 0x12, 0x26, 0x0a, 0x04, 0x56,
	0x42, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x61, 0x78, 0x6f,
	0x73, 0x6b, 0x76, 0x2e, 0x42, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x4e, 0x75, 0x6d, 0x52, 0x04, 0x56,
	0x42, 0x61, 0x6c, 0x22, 0x7d, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x28, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70,
	0x61, 0x78, 0x6f, 0x73, 0x6b, 0x76, 0x2e, 0x50, 0x61, 0x78, 0x6f, 0x73, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x52, 0x02, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x03, 0x42, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x6b,
	0x76, 0x2e, 0x42, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x4e, 0x75, 0x6d, 0x52, 0x03, 0x42, 0x61, 0x6c,
	0x12, 0x20, 0x0a, 0x03, 0x56, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x70, 0x61, 0x78, 0x6f, 0x73, 0x6b, 0x76, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x03, 0x56,
	0x61, 0x6c, 0x22, 0x4a, 0x0a, 0x0a, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x4b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x4f, 0x4b,
	0x12, 0x2c, 0x0a, 0x07, 0x4c, 0x61, 0x73, 0x74, 0x42, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x6b, 0x76, 0x2e, 0x42, 0x61, 0x6c, 0x6c,
	0x6f, 0x74, 0x4e, 0x75, 0x6d, 0x52, 0x07, 0x4c, 0x61, 0x73, 0x74, 0x42, 0x61, 0x6c, 0x32, 0x76,
	0x0a, 0x07, 0x50, 0x61, 0x78, 0x6f, 0x73, 0x4b, 0x56, 0x12, 0x36, 0x0a, 0x07, 0x50, 0x72, 0x65,
	0x70, 0x61, 0x72, 0x65, 0x12, 0x13, 0x2e, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x6b, 0x76, 0x2e, 0x50,
	0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x61, 0x78, 0x6f,
	0x73, 0x6b, 0x76, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x12, 0x33, 0x0a, 0x06, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x12, 0x12, 0x2e, 0x70, 0x61,
	0x78, 0x6f, 0x73, 0x6b, 0x76, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x13, 0x2e, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x6b, 0x76, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x1c, 0x5a, 0x1a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x6b, 0x76, 0x3b, 0x70, 0x61, 0x78,
	0x6f, 0x73, 0x6b, 0x76, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_paxoskv_proto_rawDescOnce sync.Once
	file_proto_paxoskv_proto_rawDescData = file_proto_paxoskv_proto_rawDesc
)

func file_proto_paxoskv_proto_rawDescGZIP() []byte {
	file_proto_paxoskv_proto_rawDescOnce.Do(func() {
		file_proto_paxoskv_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_paxoskv_proto_rawDescData)
	})
	return file_proto_paxoskv_proto_rawDescData
}

var file_proto_paxoskv_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_paxoskv_proto_goTypes = []interface{}{
	(*BallotNum)(nil),       // 0: paxoskv.BallotNum
	(*Value)(nil),           // 1: paxoskv.Value
	(*PaxosInstanceID)(nil), // 2: paxoskv.PaxosInstanceID
	(*PrepareReq)(nil),      // 3: paxoskv.PrepareReq
	(*PrepareResp)(nil),     // 4: paxoskv.PrepareResp
	(*AcceptReq)(nil),       // 5: paxoskv.AcceptReq
	(*AcceptResp)(nil),      // 6: paxoskv.AcceptResp
}
var file_proto_paxoskv_proto_depIdxs = []int32{
	2,  // 0: paxoskv.PrepareReq.ID:type_name -> paxoskv.PaxosInstanceID
	0,  // 1: paxoskv.PrepareReq.Bal:type_name -> paxoskv.BallotNum
	0,  // 2: paxoskv.PrepareResp.LastBal:type_name -> paxoskv.BallotNum
	1,  // 3: paxoskv.PrepareResp.Val:type_name -> paxoskv.Value
	0,  // 4: paxoskv.PrepareResp.VBal:type_name -> paxoskv.BallotNum
	2,  // 5: paxoskv.AcceptReq.ID:type_name -> paxoskv.PaxosInstanceID
	0,  // 6: paxoskv.AcceptReq.Bal:type_name -> paxoskv.BallotNum
	1,  // 7: paxoskv.AcceptReq.Val:type_name -> paxoskv.Value
	0,  // 8: paxoskv.AcceptResp.LastBal:type_name -> paxoskv.BallotNum
	3,  // 9: paxoskv.PaxosKV.Prepare:input_type -> paxoskv.PrepareReq
	5,  // 10: paxoskv.PaxosKV.Accept:input_type -> paxoskv.AcceptReq
	4,  // 11: paxoskv.PaxosKV.Prepare:output_type -> paxoskv.PrepareResp
	6,  // 12: paxoskv.PaxosKV.Accept:output_type -> paxoskv.AcceptResp
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_paxoskv_proto_init() }
func file_proto_paxoskv_proto_init() {
	if File_proto_paxoskv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_paxoskv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BallotNum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paxoskv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paxoskv_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaxosInstanceID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paxoskv_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrepareReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paxoskv_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrepareResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paxoskv_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paxoskv_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_paxoskv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_paxoskv_proto_goTypes,
		DependencyIndexes: file_proto_paxoskv_proto_depIdxs,
		MessageInfos:      file_proto_paxoskv_proto_msgTypes,
	}.Build()
	File_proto_paxoskv_proto = out.File
	file_proto_paxoskv_proto_rawDesc = nil
	file_proto_paxoskv_proto_goTypes = nil
	file_proto_paxoskv_proto_depIdxs = nil
}
